### ISSUE TITLE
Supports Javascript / typescript indexing

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/quick-question#5]
Indexer: Supports javascript / typescript through tree-sitter, might need introduce a new field in metadata for language.
Front-end: Supports syntax highlight for js/typescript.

**Comment by wsxiaoys** [comment]
https://github.com/TabbyML/quick-question/blob/6c78f447da87e3dbce6e5066e67817dd8c8f7d2c/packages/quick-question/pages/api/search.ts#L56

Language string `Python` here also requires updates with metadata.language

@icycodes

**Comment by icycodes** [comment]
> Language string `Python` here also requires updates with metadata.language

Fixed in https://github.com/TabbyML/quick-question/pull/10
